package uiswing;

import controlador.ControladorMonitor;
import dominio.Sector.Sector;
import dominio.trabajador.TrabajadorException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import vista.VistaMonitoreo;

public class MonitorLlamadas extends javax.swing.JDialog implements VistaMonitoreo {

    ControladorMonitor controlador;

    public MonitorLlamadas() {
        initComponents();
        controlador = new ControladorMonitor(this);
        jList1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_sector = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSectores = new javax.swing.JList<>();
        jLabelSectoresBold = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_sector.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_sector.setText("Aplicaciones de Monitoreo");

        jScrollPane1.setViewportView(jList1);

        jListSectores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSectoresValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListSectores);

        jLabelSectoresBold.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelSectoresBold.setText("Sectores");

        jButtonSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_sector))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabelSectoresBold))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_sector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelSectoresBold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListSectoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSectoresValueChanged
        String sectorElegido = jListSectores.getSelectedValue();
        if (sectorElegido != null) {
            try {
                elegirSector(sectorElegido);
            } catch (TrabajadorException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo avanzar: no se ha elegido ningun sector");
        }
    }//GEN-LAST:event_jListSectoresValueChanged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Desea Salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelSectoresBold;
    private javax.swing.JLabel jLabel_sector;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListSectores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTodosLosSectores(List<Sector> sectoresTotal) {
        List<String> listaSectoresArr = new ArrayList<>();
        String linea = null;
        listaSectoresArr.add("Ver las llamadas de todos los sectores");
        for (Sector sector : sectoresTotal) {
            linea = formatear(sector);
            listaSectoresArr.add(linea);
        }
        String[] array = new String[listaSectoresArr.size()];
        array = listaSectoresArr.toArray(array);
        jListSectores.setListData(array);
    }

    private String formatear(Sector sector) {
        return sector.getNombre();

    }

    private void elegirSector(String sectorElegido) throws TrabajadorException {
        List<String> llamadas = controlador.elegirSector(sectorElegido);
        String[] array = new String[llamadas.size()];
        array = llamadas.toArray(array);
        jList1.setListData(array);
    }
}
